# Generated by Django 6.0.2 on 2026-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_culturalimmersions_includes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalimmersions',
            name='price',
            field=models.CharField(max_length=100, help_text='Price per person'),
        ),
        migrations.AlterField(
            model_name='legacyportfolio',
            name='price',
            field=models.CharField(max_length=100, help_text='Price per person'),
        ),
    ]
