# Generated by Django 4.2.30 on 2026-08-15 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Signature Safari', 'Signature Safari'), ('Regenerative Adrenaline', 'Regenerative Adrenaline'), ('Coastal Retreat', 'Coastal Retreat'), ('Aerial Adventure', 'Aerial Adventure'), ('Luxury Experience', 'Luxury Experience'), ('Cultural Experience', 'Cultural Experience'), ('Other', 'Other')], default='Other', max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.CharField(help_text='Example: $18,500 or Enquire', max_length=100)),
                ('price_label', models.CharField(default='/ experience', help_text='Example: / experience or / custom experience', max_length=100)),
                ('image', models.ImageField(help_text='Upload the image for this offer.', upload_to='offers/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active offers appear on the website.')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark this offer as featured.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
