# Generated by Django 5.2.17 on 2026-08-30 10:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(help_text='Upload the image for this offer.', upload_to=app.models.upload_image_to),
        ),
    ]
