# Generated by Django 5.2.17 on 2026-09-02 13:41

import app.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalimmersions',
            name='main_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=app.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(help_text='Upload the image for this offer.', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=app.models.upload_image_to),
        ),
    ]
